### ISSUE TITLE
TipTap 2 syntax support

### ISSUE THREAD

**Issue by mmachatschek** [ueberdosis/prosemirror-php#30]
Hi @hanspagel,

when updating the tiptap editor to version 2 [you are forced](https://www.tiptap.dev/overview/upgrade-guide#new-names-for-most-extensions) to use lower camel cased syntax for the node types. The "prosemirror to html" way is pretty easy to support, but for "html to prosemirror" their would be a breaking change in the library imo.

I opened this PR https://github.com/ueberdosis/prosemirror-to-html/pull/57
Maybe we can add some configuration like:

```
\ProseMirror\ProseMirror::htmlToJson('<p>Example Text</p>', true);
```

This would tell the renderer of html-to-prosemirror to use the new syntax style instead of the old one.

What do you think?

**Comment by hanspagel** [comment]
Yes! You're right! I had two solutions in mind:

1. A new major version of all the packages.
2. A complete rewrite, as `tiptap-php` (I have tons of ideas …)

But maybe the flag is the easiest way. Let me think about this!

**Comment by mmachatschek** [comment]
I'm actually writing a PR for the html-to-prosemirror version at the very moment. Just let me know what you think about it as soon as its online 👍

**Comment by mmachatschek** [comment]
Already sent it in 😅 

I kind of went with the same approach as you did. I just tell it that it should use `withLowerCamelCasedSyntax`. 

Are there any plans of introducing any new "major" changes to the JSON syntax? Because splitting it in custom classes feels a little bit to much overhead I think

**Comment by hanspagel** [comment]
A short follow-up: I decided to rewrite the package. I’ll need some more time, but I think it’s worth it. Sneekpeak:

```php
$html = (new Tiptap\Editor)->setContent([
    'type' => 'doc',
    'content' => [
        [
            'type' => 'paragraph',
            'content' => [
                [
                    'type' => 'text',
                    'text' => 'Example Text',
                ],
            ]
        ]
    ],
])->getHTML();
```

**Comment by mmachatschek** [comment]
@hanspagel can I help in any way with this?

**Comment by hanspagel** [comment]
Thanks for the offer! I’ll try to find some time to publish the new package on GitHub & packagist (as an alpha version) and leave everything that’s open as issues. ✌️

**Comment by mmachatschek** [comment]
@hanspagel just a friendly reminder if you could find some time to publish this? I would happily help with the open issues

**Comment by hanspagel** [comment]
Thanks for the reminder! I’m struggling with life, but I’ve sent you an invite to the repo. You can clone it and run PHPUnit to see what’s the biggest issue with the new HTML renderer. I’ve rewrote it to use the PHP DOM api, but reintroduced a bug I recently fixed in the old renderer (https://github.com/ueberdosis/prosemirror-to-html/issues/50).

If you have an idea how to fix that: Amazing! If not, I’ll probably go back to the old way of rendering HTML. And I have few ideas to improve everything. The biggest change is probably putting both packages into one and having one class for every node (instead of two different classes for both ways).

**Comment by mmachatschek** [comment]
Sorry to hear that. Hope everything gets better for you soon!

I'm looking into this and try to help at every end :+1: 

Cheers, Markus!

**Comment by hanspagel** [comment]
Done here: https://github.com/ueberdosis/tiptap-php
